### ISSUE TITLE
Refactor storage API

### ISSUE THREAD

**Issue by bklang** [adhearsion/voicemail#21]
When working with voicemail storage we have to dynamically construct method names, like this: https://github.com/adhearsion/voicemail/blob/develop/lib/voicemail/call_controllers/mailbox_messages_controller.rb#L36

The API should allow specifying the message type as an argument instead of requiring different method names.  This also allows other who subclass this to be able to use different labels that we do not natively provide.

**Comment by JustinAiken** [comment]
>  This also allows other who subclass this to be able to use different labels that we do not natively provide.

I like it; could be an "archive" mailbox and a "super-important" mailbox if they like...

Hmm, that would change the API enough to necessitate a bump to 2.0.0 to stay Sem-compliant...

**Comment by wdrexler** [comment]
Here's my take on what the new storage API should look like.
- Replace `next_new_message(mailbox_id)` and `next_saved_message(mailbox_id)` with `next_message(mailbox_id, type)`.
- Same as above, except with `count_messages(mailbox_id, type)`
  These changes would allow for much easier reading (and adding of new features) to the call controllers, so instead of

``` Ruby
storage_instance.send "next_#{new_or_saved}_message", mailbox[:id]
```

we get

``` Ruby
storage_instance.next_message mailbox[:id], new_or_saved
```

The next one I'm not really sure about, but `delete_message` needs a facelift.  I'm thinking it could look either something like:

``` Ruby
storage_instance.delete_message mailbox[:id], message, :new
```

or

``` Ruby
storage_instance.delete_message mailbox[:id], message[:id], :new
```

or even

``` Ruby
storage_instance.delete mailbox[:id], message[:id]
```

since each message has its own UUID, and those shouldn't overlap.  Anyways, I'm open to suggestions. @bklang @polysics @JustinAiken, let me know what you think!

**Comment by bklang** [comment]
Looks about right to me.

> storage_instance.delete_message mailbox[:id], message, :new
> or
> 
> storage_instance.delete_message mailbox[:id], message[:id], :new
> or even
> 
> storage_instance.delete mailbox[:id], message[:id]

The middle one. If the message is a UUID let's not quibble about what state it's in. Just delete it.

**Comment by JustinAiken** [comment]
Sounds good to me.  We'll also need to change `#archive_message` and `#unarchive_message` to something more generic, like `#change_message_state message[:id], :new, :saved`
