### ISSUE TITLE
Two ways to play a message intro

### ISSUE THREAD

**Issue by wdrexler** [adhearsion/voicemail#37]
As of right now, we have two classes:
https://github.com/adhearsion/voicemail/blob/develop/lib/voicemail/intro_message_creator.rb
and 
https://github.com/adhearsion/voicemail/blob/develop/lib/voicemail/call_controllers/mailbox_play_message_intro_controller.rb
That both perform roughly the same function. The only difference is that one of them is a CallController, and the other is not. Which one should we use? I'm leaning towards the CallController, simply because using the one that is not a CallController will require duplicating functionality included in adhearsion-i18n (the `AdhearsionI18n#t` method is only available to CallControllers). Thoughts, @bklang, @JustinAiken, @polysics?

**Comment by JustinAiken** [comment]
Looks like a merge error somewhere... All of the code around creating message prompts was moved into `IntroMessageCreator`, a service class I created to move some of the complexity of constructing the prompt out of the controller - the call controller that called it used be small since all the logic was in there...

After I take a shower I'll go look through the history, see if I can remember/see what happened...

**Comment by JustinAiken** [comment]
Aah; `MailboxPlayMessageIntroController` isn't even called/referenced anywhere; `MailboxPlayMessageController` has a [`#intro_message` method](https://github.com/adhearsion/voicemail/blob/76338268ba0c8079bca93b96d743cdd72ee3b0f7/lib/voicemail/call_controllers/mailbox_play_message_controller.rb#L45) that calls `IntroMessageCreator`...

I'd say delete `MailboxPlayMessageIntroController` and it's spec entirely, and just clean up the service object to use adhearsion-i8n..

**Comment by bklang** [comment]
Fixed by #38
